In [1]:
minha_lista = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr=np.array(minha_lista)

In [5]:
arr

array([1, 2, 3])

In [6]:
minha_mat = [[1,2,3],[1,2,3],[1,2,3]]

In [7]:
np.array(minha_mat)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

O jeito mais comum de criar um numpy array é usando

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# gerar array 2x2 de zeros
np.zeros((5,5)) 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#Gerar array de um
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
#np.linspace() gerar array de números com o número de espaços entre as variáveis
np.linspace(0,5,100)


array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)
#Cria matriz identidade

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#gerar random números de uma distribuição normal centrada em um
np.random.rand(5)

array([0.27353255, 0.28145622, 0.34826547, 0.61805385, 0.05542287])

In [22]:
np.random.rand(5,5)

array([[0.20354401, 0.64885712, 0.99199806, 0.80804719, 0.62588957],
       [0.17585321, 0.54173974, 0.46177857, 0.20025441, 0.107608  ],
       [0.11986892, 0.924693  , 0.6052468 , 0.94195896, 0.53876185],
       [0.43633105, 0.20982984, 0.9909151 , 0.46875606, 0.61204225],
       [0.33543794, 0.16986812, 0.93629201, 0.18534849, 0.83038651]])

In [23]:
#gerar random números de uma distribuição normal centrada em 0
np.random.randn(5)

array([ 0.09338899, -1.06196949, -0.23024376,  0.09414306,  1.43566124])

In [24]:
np.random.randn(4,4)

array([[-0.68895962,  1.1691476 ,  0.68068922,  0.51684783],
       [-0.37438065, -0.58422682, -2.16593726,  0.47455067],
       [ 0.88458288, -0.57823126, -1.99678571,  1.39520989],
       [-0.22998215, -1.10415979,  0.75405804, -0.95361619]])

In [26]:
#Gerar random de inteiros
np.random.randint(1,100)

38

In [27]:
np.random.randint(1,100,10)

array([89, 46, 33, 45, 86, 62, 38, 43, 67, 93])

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr= np.random.randint(0,50,10)

In [33]:
ranarr

array([22, 40, 39, 18, 20, 32, 35, 11, 46,  4])

In [34]:
#reshape server parar rearragar o arrau em matriz
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max() #acha valor máximo

46

In [38]:
ranarr.min() #acha valor minimo

4

In [39]:
ranarr.argmax() #achar o index do valor máximo

8

In [40]:
ranarr.argmin() #achar o index do valor mínimo

9

In [41]:
arr.shape #mostra o shape do array

(25,)

In [42]:
arr=arr.reshape(5,5)

In [43]:
arr.shape


(5, 5)

In [44]:
arr.dtype #mostra o tipo dos dados do array

dtype('int32')

In [45]:
from numpy.random import randint # facilitar para não ter que digitar np. todas as vezes para determinads funções

In [46]:
randint(2,10)

8